### ISSUE TITLE
milestone 3

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/chemcalculator#33]
1. Documentation
- [x] deployed by ReadTheDocs
- [x] docstrings for all functions should be rendered using the napolean Sphinx extnesion
- [x] documentation include a demonstration of how to use each function in the package
- [x] add dependencies to pyproject.toml

2. GitHub actions workflow
- [x] the workflow in .github/workflows/ci-cd.yml configured so it runs the test suite and style checkers on pushes and pull requests
- [x] deploys to TestPyPI on pushes to your project’s repository’s deployment branch (typically the main branch).  
- [x] change readme for the correct installation instruction

might need to change in .github/workflows/ci-cd.yml file:
- [x] Ensure the deployment branch (typically the main branch) is correctly specified on lines 6, 9 and 42
- [x] Ensure that the correct Python version is listed on line 19 (it should match the version in your pyproject.toml file)
- [x] If codecov step is not working, set fail_ci_if_error: false in line 34.

**Comment by Kingslin0810** [comment]
I pushed the ci-cd.yml to update ci-cd.yml without updating cdecov token using the ci-cd branch.

On a second thought, would those workflow ci-cd.yml files be using "main" branch to update?

**Comment by Kingslin0810** [comment]
When I run `poetry run sphinx-apidoc -f -o docs/source chemcalculator` I got the error that 'it's not in directory'; still not sure of how to create `/rst` files for our package functions.
